### ISSUE TITLE
System.IO.PathTooLongException

### ISSUE THREAD

**Issue by ghost** [mongodb-js/electron-installer-squirrel-windows#12]
Here is full error
**System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.**
 Program successfully creates nupkg file. Then gives error while executing this command;
C:\Users\sahip\AppData\Roaming\npm\node_modules\electron-installer-squirrel-windows\vendor\Update.com --releasify C:\Users\sahip\AppData\Local\Temp\ClientNode.0.1.0.nupkg --releaseDir C:\ --loadingGif C:\Users\sahip\AppData\Roaming\npm\node_modules\electron-installer-squirrel-windows\resources\install-spinner.gif

I am using Win7 64 Bit

Any idea?

**Comment by ghost** [comment]
Update:
Here is what I did;
I changed temp dir to c:\tmp
I moved npm dir to c:\npm(And also changed PATH to new npm path)
I changed "electron-installer-squirrel-windows" to "eisw" (And also in node_modules)
I started the command like that
**C:\cn>eisw .\ --debug --loading_gif c:\is.gif**

The failed command in logs is ;
_C:\npm\node_modules\eisw\vendor\Update.com --releasify C:\temp\ClientNode.
0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif_

I executed this command manually with no errors.
It does not seem Long path problem.

Output;

`C:\cn>eisw .\ --debug --loading_gif c:\is.gif
  electron-installer-squirrel-windows generating squirrel-windows installer for
+0ms {
  "_": [
    ".\"
  ],
  "debug": true,
  "overwrite": false,
  "loading_gif": "c:\is.gif",
  "path": ".\"
}
[Error: 'ClientNode.0.1.0.nupkg' already exists! Run electron-installer-squirrel
-windows again with '--overwrite' or just remove the file at 'C:\ClientNode.0.1.
0.nupkg' yourself and run again.]

C:\cn>eisw .\ --debug --loading_gif c:\is.gif
  electron-installer-squirrel-windows generating squirrel-windows installer for
+0ms {
  "_": [
    ".\"
  ],
  "debug": true,
  "overwrite": false,
  "loading_gif": "c:\is.gif",
  "path": ".\"
}
  electron-installer-squirrel-windows creating temp directory +31ms
  electron-installer-squirrel-windows generating .nuspec file contents +0ms
  electron-installer-squirrel-windows .nuspec file contents:
 +0ms ?<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ClientNode</id>
    <title>ClientNode</title>
    <version>0.1.0</version>
    <authors>Nokta</authors>
    <owners>Nokta</owners>
    <iconUrl>https://raw.githubusercontent.com/atom/electron/master/atom/browser
/resources/win/atom.ico</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Gateway ClientNode</description>
    <copyright>2016 Nokta</copyright>
  </metadata>
  <files>
    <file src="locales\**" target="lib\net45\locales" />
    <file src="resources\**" target="lib\net45\resources" />
    <file src="*.bin" target="lib\net45" />
    <file src="*.dll" target="lib\net45" />
    <file src="*.pak" target="lib\net45" />
    <file src="Update.exe" target="lib\net45\squirrel.exe" />
    <file src="icudtl.dat" target="lib\net45\icudtl.dat" />
    <file src="LICENSE" target="lib\net45\LICENSE" />
    <file src="ClientNode.exe" target="lib\net45\ClientNode.exe" />
  </files>
</package>
  electron-installer-squirrel-windows writing nuspec file to 'C:\temp\ClientNode
.nuspec' +16ms
  electron-installer-squirrel-windows copying 'C:\npm\node_modules\eisw\vendor\U
pdate.exe' -> 'Update.exe' +0ms
  electron-installer-squirrel-windows generating 'C:\temp'... +31ms
  electron-installer-squirrel-windows exec 'C:\npm\node_modules\eisw\vendor\nuge
t.exe' with args 'pack C:\temp\ClientNode.nuspec -BasePath .\ -OutputDirectory C
:\temp -NoDefaultExcludes' +0ms
stdout Attempting to build package from 'ClientNode.nuspec'.
Successfully created package 'C:\temp\ClientNode.0.1.0.nupkg'.
  electron-installer-squirrel-windows no remote releases.  skipping sync. +4m
  electron-installer-squirrel-windows exec 'C:\npm\node_modules\eisw\vendor\Upda
te.com' with args '--releasify C:\temp\ClientNode.0.1.0.nupkg --releaseDir C:\ -
-loadingGif c:\is.gif' +0ms
Error  { [Error: Command failed: C:\npm\node_modules\eisw\vendor\Update.com --re
leasify C:\temp\ClientNode.0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif
System.IO.PathTooLongException: The specified path, file name, or both are too l
ong. The fully qualified file name must be less than 260 characters, and the dir
ectory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Squirrel.ReleasePackage.extractZipDecoded(String zipFilePath, String outFo
lder)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func'2 releaseNotesProcessor, Action'1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
]
  killed: false,
  code: 4294967295,
  signal: null,
  cmd: 'C:\npm\node_modules\eisw\vendor\Update.com --releasify C:\temp\Cl
ientNode.0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif' }
System.IO.PathTooLongException: The specified path, file name, or both are too l
ong. The fully qualified file name must be less than 260 characters, and the dir
ectory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Squirrel.ReleasePackage.extractZipDecoded(String zipFilePath, String outFo
lder)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func'2 releaseNotesProcessor, Action'1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args
stdout
{ [Error: Command failed: C:\npm\node_modules\eisw\vendor\Update.com --releasify
 C:\temp\ClientNode.0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif
System.IO.PathTooLongException: The specified path, file name, or both are too l
ong. The fully qualified file name must be less than 260 characters, and the dir
ectory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at Squirrel.ReleasePackage.extractZipDecoded(String zipFilePath, String outFo
lder)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func'2 releaseNotesProcessor, Action'1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
]
  killed: false,
  code: 4294967295,
  signal: null,
  cmd: 'C:\npm\node_modules\eisw\vendor\Update.com --releasify C:\temp\Cl
ientNode.0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif' }

C:\cn>C:\npm\node_modules\eisw\vendor\Update.com --releasify C:\temp\ClientNode.
0.1.0.nupkg --releaseDir C:\ --loadingGif c:\is.gif

C:\cn>`

**Comment by santomegonzalo** [comment]
You could fix this problem if you use asar because if you don't use it windows will go to every package that you have inside node_modules and that could be huge... if you use asar its just like a zip so the packager will not look on every folder

**Comment by BastienvP3** [comment]
Maybe we could use the \\?\ reference for long paths?

**Comment by JenRobertson** [comment]
I fixed this by adding the following line to my package.json:
``` 
  "config": {
    "forge": {
      "packagerConfig": {
        "asar": true
      },
```

**Comment by amiranagram** [comment]
@JenRobertson Thanks a lot.

**Comment by erikyuzwa** [comment]
confirmed - this worked with `^6.0.0-beta.54`  - thanks @JenRobertson !
